departments = {'aceng': 'ac eng',
               'arthis': 'art his',
               'biosci': 'bio sci',
               'chclat': 'chc/lat',
               'cltthy': 'clt&thy',
               'comlit': 'com lit',
               'crmlaw': 'crm/law',
               'devbio': 'dev bio',
               'easian': 'e asian',
               'ecoevo': 'eco evo',
               'edaff': 'ed aff',
               'ermed': 'er med',
               'eurost': 'euro st',
               'fammed': 'fam med',
               'flmmda': 'flm&mda',
               'gensex': 'gen&sex',
               'glblme': 'glbl me',
               'ics': 'i&c sci',
               'intmed': 'int med',
               'intlst': 'intl st',
               'litjrn': 'lit jrn',
               'mmg': 'm&mg',
               'meded': 'med ed',
               'medhum': 'med hum',
               'mgmtep': 'mgmt ep',
               'mgmtfe': 'mgmt fe',
               'mgmthc': 'mgmt hc',
               'micbio': 'mic bio',
               'molbio': 'mol bio',
               'netsys': 'net sys',
               'nursci': 'nur sci',
               'obgyn': 'ob/gyn',
               'pedgen': 'ped gen',
               'physci': 'phy sci',
               'pmr': 'pm&r',
               'polsci': 'pol sci',
               'ppd': 'pp&d',
               'psybeh': 'psy beh',
               'pubpol': 'pub pol',
               'radsci': 'rad sci',
               'relstd': 'rel std',
               'socsci': 'soc sci',
               'uniaff': 'uni aff',
               'unistu': 'uni stu',
               'visstd': 'vis std',
               'womnst': 'womn st'
               }


def lookup(name) -> str:
    return departments.get(name, name)
